export const Topics = {
    USER_CREATED: "USER_CREATED",
    USER_UPDATED: "USER_UPDATED",
    EXPENSE_CREATED: "EXPENSE_CREATED",
    EXPENSE_UPDATED: "EXPENSE_UPDATED",
    EXPENSE_DELETED: "EXPENSE_DELETED",
}